version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.4-node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: 'gem update bundler && bundle install'
  linters:
    docker:
      - image: cimg/ruby:3.0.4-node
    steps:
      - checkout
      - run:
          name: Run Rubocop
          command: 'gem update bundler && bundle install && bundle exec rubocop'
  test:
    docker:
      - image: cimg/ruby:3.0.4-node
    steps:
      - checkout
      - run:
          name: Run Rspec
          command: 'gem update bundler && bundle install && bundle exec rspec'
workflows:
  build_and_test:
    jobs:
      - build
      - linters
      - test:
          requires:
            - build
            - linters
